import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs"
import { join } from "node:path"
import { PNG } from "pngjs"
import {
  animatedSpriteIds,
  animationFrameCount,
  sourceTileSize,
  spriteAnimations,
  staticSpriteCrops,
  type AnimatedSpriteId,
  type SpriteAnimationId,
} from "../src/assets/opendungeonSprites.js"

type Rgba = [number, number, number, number]
type Rgb = [number, number, number]

type ActorPalette = {
  skin: Rgb
  armor: Rgb
  dark: Rgb
  cloth: Rgb
  accent: Rgb
  glow: Rgb
  weapon: Rgb
}

const outDir = "assets/opendungeon"
const logicalTileSize = 32
const size = logicalTileSize
const upscaleFactor = sourceTileSize / logicalTileSize
const transparent: Rgba = [0, 0, 0, 0]
const outline: Rgb = [9, 8, 13]
const itchCacheRoot = ".asset-cache/itch/extracted"
const openGameArtD20Root = ".asset-cache/opengameart-d20"

if (!Number.isInteger(upscaleFactor) || upscaleFactor < 1) {
  throw new Error(`sourceTileSize must be a positive multiple of ${logicalTileSize}`)
}

const palettes: Record<AnimatedSpriteId, ActorPalette> = {
  "hero-ranger": {
    skin: [198, 124, 72],
    armor: [36, 54, 65],
    dark: [20, 28, 35],
    cloth: [45, 91, 78],
    accent: [238, 199, 92],
    glow: [132, 232, 164],
    weapon: [164, 118, 74],
  },
  "hero-warden": {
    skin: [188, 114, 76],
    armor: [78, 86, 98],
    dark: [22, 25, 31],
    cloth: [73, 57, 75],
    accent: [209, 166, 91],
    glow: [143, 213, 235],
    weapon: [193, 184, 166],
  },
  "hero-arcanist": {
    skin: [176, 118, 88],
    armor: [39, 29, 58],
    dark: [15, 12, 26],
    cloth: [75, 48, 111],
    accent: [227, 119, 203],
    glow: [90, 210, 255],
    weapon: [174, 139, 92],
  },
  "npc-smith": {
    skin: [205, 133, 82],
    armor: [89, 75, 63],
    dark: [31, 24, 21],
    cloth: [103, 50, 37],
    accent: [229, 126, 58],
    glow: [255, 176, 74],
    weapon: [166, 151, 126],
  },
  "npc-oracle": {
    skin: [188, 143, 112],
    armor: [43, 39, 66],
    dark: [18, 16, 30],
    cloth: [63, 76, 105],
    accent: [220, 202, 160],
    glow: [169, 227, 255],
    weapon: [139, 121, 92],
  },
  slime: {
    skin: [89, 190, 130],
    armor: [48, 120, 92],
    dark: [10, 39, 35],
    cloth: [42, 100, 78],
    accent: [159, 244, 170],
    glow: [125, 255, 178],
    weapon: [92, 164, 124],
  },
  ghoul: {
    skin: [165, 176, 168],
    armor: [63, 70, 78],
    dark: [18, 21, 25],
    cloth: [55, 46, 49],
    accent: [208, 72, 89],
    glow: [198, 229, 226],
    weapon: [130, 135, 140],
  },
  necromancer: {
    skin: [154, 117, 161],
    armor: [31, 22, 43],
    dark: [14, 11, 23],
    cloth: [70, 35, 91],
    accent: [206, 82, 185],
    glow: [85, 218, 245],
    weapon: [145, 118, 86],
  },
  "boss-forgemaster": {
    skin: [174, 82, 55],
    armor: [91, 74, 61],
    dark: [26, 18, 17],
    cloth: [82, 30, 25],
    accent: [243, 111, 53],
    glow: [255, 194, 88],
    weapon: [174, 146, 106],
  },
  "boss-lich": {
    skin: [138, 166, 183],
    armor: [36, 29, 57],
    dark: [12, 10, 24],
    cloth: [61, 43, 96],
    accent: [220, 74, 203],
    glow: [95, 223, 255],
    weapon: [166, 137, 91],
  },
  "boss-minotaur": {
    skin: [145, 82, 57],
    armor: [65, 56, 57],
    dark: [21, 16, 17],
    cloth: [87, 42, 31],
    accent: [213, 161, 83],
    glow: [255, 103, 72],
    weapon: [174, 160, 138],
  },
}

mkdirSync(outDir, { recursive: true })
writeTerrainSheet()
writeItemSheet()
writeActorSheet()
writeD20Sheet()
writeFileSync(
  join(outDir, "SOURCE.txt"),
  [
    `opendungeon ${sourceTileSize}x${sourceTileSize} RGBA sprite sheets generated by scripts/generate-opendungeon-assets.ts`,
    `Terrain, items, bosses, and NPCs are project-authored procedural pixel art from ${logicalTileSize}x${logicalTileSize} logical tiles.`,
    "Hero/enemy rows use cached free Itch reference packs when present: Zerie Tiny RPG Character Asset Pack, Mattz Art Samurai 2D Pixel Art, and MonoPixelArt Forest Monsters.",
    "D20 rows use cached OpenGameArt CC0 rolling-animation frames when present.",
    "The caches live in .asset-cache/itch and .asset-cache/opengameart-d20 and are intentionally not committed.",
    "",
  ].join("\n"),
  "utf8",
)

function writeTerrainSheet() {
  const sheet = createSheet(8, 1, false)
  drawTile(sheet, 0, 0, (tile) => floor(tile, 0))
  drawTile(sheet, 1, 0, (tile) => floor(tile, 1))
  drawTile(sheet, 2, 0, (tile) => floor(tile, 2))
  drawTile(sheet, 3, 0, (tile) => wall(tile, 0))
  drawTile(sheet, 4, 0, (tile) => wall(tile, 1))
  drawTile(sheet, 5, 0, stairs)
  drawTile(sheet, 6, 0, door)
  drawTile(sheet, 7, 0, voidTile)
  savePng(sheet, "terrain.png")
}

function writeItemSheet() {
  const sheet = createSheet(8, 3, true)
  const order = Object.entries(staticSpriteCrops)
    .filter(([, crop]) => crop.sheet === "items")
    .sort((a, b) => a[1].tileY - b[1].tileY || a[1].tileX - b[1].tileX)

  for (const [id, crop] of order) {
    drawTile(sheet, crop.tileX, crop.tileY, (tile) => item(tile, id))
  }

  savePng(sheet, "items.png")
}

function writeActorSheet() {
  const rows = animatedSpriteIds.length * spriteAnimations.length
  const sheet = createSheet(4, rows, true)

  animatedSpriteIds.forEach((id, actorIndex) => {
    spriteAnimations.forEach((animation, animationIndex) => {
      for (let frame = 0; frame < 4; frame++) {
        drawTile(sheet, frame, actorIndex * spriteAnimations.length + animationIndex, (tile) => actor(tile, id, animation, frame))
      }
    })
  })

  savePng(sheet, "actors.png")
}

function writeD20Sheet() {
  const sheet = createSheet(12, 20, true)
  for (let result = 1; result <= 20; result++) {
    for (let frame = 0; frame < 12; frame++) drawTile(sheet, frame, result - 1, (tile) => drawD20Frame(tile, result, frame))
  }
  savePng(sheet, "d20.png")
}

function floor(tile: PNG, variant: number) {
  const base = variant === 0 ? [42, 55, 61] : variant === 1 ? [48, 63, 68] : [39, 51, 58]
  fill(tile, 0, 0, size, size, [...base, 255])
  for (let y = 0; y < size; y += 8) line(tile, 0, y, size - 1, y, darken(base, 0.72))
  for (let x = variant * 3; x < size; x += 11) line(tile, x, 0, x, size - 1, darken(base, 0.82))
  scatter(tile, variant + 5, lighten(base, 1.18), darken(base, 0.7))
  if (variant === 2) {
    line(tile, 6, 22, 14, 17, darken(base, 0.55))
    line(tile, 15, 17, 25, 20, darken(base, 0.55))
  }
}

function wall(tile: PNG, variant: number) {
  const base = variant === 0 ? [79, 74, 86] : [69, 64, 76]
  fill(tile, 0, 0, size, size, [...base, 255])
  for (let row = 0; row < 4; row++) {
    const y = row * 8
    line(tile, 0, y, size - 1, y, darken(base, 0.56))
    for (let x = row % 2 ? 8 : 0; x < size; x += 16) line(tile, x, y, x, y + 7, darken(base, 0.6))
    fill(tile, 2 + ((row + variant) % 2) * 10, y + 2, 8, 4, [...lighten(base, 1.14), 255])
  }
  rect(tile, 1, 1, size - 2, size - 2, darken(base, 0.48), false)
  scatter(tile, variant + 13, lighten(base, 1.08), darken(base, 0.62))
}

function stairs(tile: PNG) {
  floor(tile, 1)
  for (let i = 0; i < 5; i++) {
    fill(tile, 7 + i * 3, 21 - i * 3, 16 - i * 2, 3, [166, 141, 91, 255])
    line(tile, 7 + i * 3, 20 - i * 3, 22 + i, 20 - i * 3, [86, 68, 51])
  }
}

function door(tile: PNG) {
  wall(tile, 0)
  fill(tile, 9, 7, 14, 22, [96, 62, 46, 255])
  rect(tile, 9, 7, 14, 22, [35, 24, 20], false)
  fill(tile, 11, 9, 10, 4, [132, 85, 55, 255])
  fill(tile, 19, 18, 2, 2, [230, 184, 91, 255])
}

function voidTile(tile: PNG) {
  fill(tile, 0, 0, size, size, [5, 7, 10, 255])
  for (let i = 0; i < 26; i++) {
    const x = (i * 13 + 5) % size
    const y = (i * 17 + 11) % size
    set(tile, x, y, [12, 23, 28, 255])
  }
}

function item(tile: PNG, id: string) {
  switch (id) {
    case "potion":
      bottle(tile, [213, 107, 140], [136, 61, 92])
      break
    case "relic":
      diamondRelic(tile)
      break
    case "chest":
      chest(tile)
      break
    case "coin":
      ellipse(tile, 10, 9, 22, 23, [93, 65, 25], true)
      ellipse(tile, 11, 8, 21, 20, [236, 191, 77], true)
      line(tile, 13, 14, 19, 14, [112, 79, 31])
      break
    case "scroll":
      scroll(tile)
      break
    case "focus-gem":
      diamond(tile, 16, 15, 9, [117, 255, 178])
      diamond(tile, 16, 15, 5, [207, 255, 226])
      break
    case "ember":
      flame(tile, 16, 16, [255, 95, 58], [255, 202, 85])
      break
    case "sword":
      sword(tile, 7, 24, 24, 7)
      break
    case "bow":
      arc(tile, 10, 6, 22, 27, [170, 117, 66])
      line(tile, 11, 7, 21, 26, [218, 210, 179])
      break
    case "staff":
      line(tile, 10, 26, 21, 6, [143, 106, 64])
      diamond(tile, 22, 6, 5, [98, 219, 255])
      break
    case "dagger":
      sword(tile, 11, 22, 21, 10)
      break
    case "axe":
      line(tile, 10, 27, 21, 6, [139, 91, 58])
      fill(tile, 17, 5, 9, 7, [184, 178, 160, 255])
      rect(tile, 17, 5, 9, 7, outline, false)
      break
    case "shield":
      shield(tile)
      break
    case "armor":
      fill(tile, 10, 8, 12, 16, [88, 91, 105, 255])
      rect(tile, 10, 8, 12, 16, outline, false)
      fill(tile, 12, 10, 8, 4, [130, 138, 151, 255])
      break
    case "key":
      ellipse(tile, 9, 11, 17, 19, [229, 190, 83], false)
      line(tile, 16, 15, 25, 15, [229, 190, 83])
      line(tile, 23, 15, 23, 19, [229, 190, 83])
      break
    case "map":
      fill(tile, 8, 9, 17, 14, [197, 170, 126, 255])
      rect(tile, 8, 9, 17, 14, [75, 55, 43], false)
      line(tile, 11, 14, 22, 12, [111, 85, 65])
      line(tile, 12, 18, 20, 20, [111, 85, 65])
      break
    case "trap":
      for (let i = 0; i < 4; i++) triangle(tile, 7 + i * 5, 24, 10 + i * 5, 15, 13 + i * 5, 24, [137, 142, 151])
      break
    case "dice":
      d20(tile, 20, 3)
      break
  }
}

function actor(tile: PNG, id: AnimatedSpriteId, animation: SpriteAnimationId, frame: number) {
  if (drawItchActor(tile, id, animation, frame)) return
  if (id === "slime") {
    slime(tile, palettes[id], animation, frame)
    return
  }
  humanoid(tile, id, palettes[id], animation, frame)
}

type ItchActorSource = {
  path: string
  frameWidth: number
  frameHeight: number
  frameCount?: number
  crop?: { x: number; y: number; width: number; height: number }
}

function drawItchActor(tile: PNG, id: AnimatedSpriteId, animation: SpriteAnimationId, frame: number) {
  const source = itchActorSource(id, animation)
  if (!source || !existsSync(source.path)) return false

  const png = PNG.sync.read(readFileSync(source.path))
  const frameCount = source.frameCount ?? Math.max(1, Math.floor(png.width / source.frameWidth))
  const sourceFrame = Math.min(frameCount - 1, Math.floor((frame / animationFrameCount) * frameCount))
  const crop = source.crop ?? { x: 0, y: 0, width: source.frameWidth, height: source.frameHeight }
  drawSourceFrame(tile, png, sourceFrame * source.frameWidth + crop.x, crop.y, crop.width, crop.height)
  return true
}

function itchActorSource(id: AnimatedSpriteId, animation: SpriteAnimationId): ItchActorSource | null {
  if (id === "hero-ranger") return zerieSource("Soldier", animation)
  if (id === "hero-warden") return samuraiSource(animation)
  if (id === "slime") return forestMushroomSource(animation)
  if (id === "ghoul" || id === "necromancer") return zerieSource("Orc", animation)
  return null
}

function zerieSource(actorName: "Soldier" | "Orc", animation: SpriteAnimationId): ItchActorSource {
  const file = zerieAnimationFile(actorName, animation)
  return {
    path: join(
      itchCacheRoot,
      "zerie",
      "Tiny RPG Character Asset Pack v1.03 -Free Soldier&Orc",
      "Characters(100x100)",
      actorName,
      actorName,
      file,
    ),
    frameWidth: 100,
    frameHeight: 100,
    crop: { x: 18, y: 12, width: 64, height: 76 },
  }
}

function zerieAnimationFile(actorName: "Soldier" | "Orc", animation: SpriteAnimationId) {
  const attack = actorName === "Soldier" ? "Attack03" : "Attack02"
  const map: Record<SpriteAnimationId, string> = {
    idle: `${actorName}-Idle.png`,
    walk: `${actorName}-Walk.png`,
    "attack-melee": `${actorName}-${actorName === "Soldier" ? "Attack01" : "Attack01"}.png`,
    "attack-ranged": `${actorName}-${attack}.png`,
    cast: `${actorName}-${attack}.png`,
    talk: `${actorName}-Idle.png`,
    shocked: `${actorName}-Hurt.png`,
    hurt: `${actorName}-Hurt.png`,
    death: `${actorName}-Death.png`,
  }
  return map[animation]
}

function samuraiSource(animation: SpriteAnimationId): ItchActorSource {
  const file =
    animation === "attack-melee" || animation === "attack-ranged" || animation === "cast"
      ? "ATTACK 1.png"
      : animation === "hurt" || animation === "shocked" || animation === "death"
        ? "HURT.png"
        : animation === "walk"
          ? "RUN.png"
          : "IDLE.png"
  return {
    path: join(itchCacheRoot, "samurai", "FREE_Samurai 2D Pixel Art v1.2", "Sprites", file),
    frameWidth: 96,
    frameHeight: 96,
    crop: { x: 16, y: 12, width: 64, height: 72 },
  }
}

function forestMushroomSource(animation: SpriteAnimationId): ItchActorSource {
  const file =
    animation === "attack-melee" || animation === "attack-ranged" || animation === "cast"
      ? "Mushroom-Attack.png"
      : animation === "hurt"
        ? "Mushroom-Hit.png"
        : animation === "death"
          ? "Mushroom-Die.png"
          : animation === "shocked"
            ? "Mushroom-Stun.png"
            : animation === "walk"
              ? "Mushroom-Run.png"
              : "Mushroom-Idle.png"
  return {
    path: join(itchCacheRoot, "forest", "Forest_Monsters_FREE", "Mushroom", "Mushroom without VFX", file),
    frameWidth: 80,
    frameHeight: 64,
    crop: { x: 4, y: 0, width: 72, height: 64 },
  }
}

function drawSourceFrame(tile: PNG, src: PNG, sx: number, sy: number, sw: number, sh: number) {
  const bounds = sourceBounds(src, sx, sy, sw, sh)
  if (!bounds) return

  const scale = Math.min((size - 6) / bounds.width, (size - 4) / bounds.height)
  const width = Math.max(1, Math.floor(bounds.width * scale))
  const height = Math.max(1, Math.floor(bounds.height * scale))
  const ox = Math.floor((size - width) / 2)
  const oy = Math.floor(size - height)

  for (let y = 0; y < height; y++) {
    for (let x = 0; x < width; x++) {
      const sourceX = bounds.x + Math.min(bounds.width - 1, Math.floor(x / scale))
      const sourceY = bounds.y + Math.min(bounds.height - 1, Math.floor(y / scale))
      const sourceIndex = (src.width * sourceY + sourceX) << 2
      const alpha = src.data[sourceIndex + 3]
      if (alpha < 24) continue
      set(tile, ox + x, oy + y, [src.data[sourceIndex], src.data[sourceIndex + 1], src.data[sourceIndex + 2], alpha])
    }
  }
}

function drawMaskedSourceFrame(
  tile: PNG,
  src: PNG,
  sx: number,
  sy: number,
  sw: number,
  sh: number,
  predicate: (src: PNG, x: number, y: number) => boolean,
  tint?: (r: number, g: number, b: number) => Rgb,
) {
  const bounds = sourceBounds(src, sx + 96, sy + 96, sw - 192, sh - 192, predicate)
  if (!bounds) return

  const scale = Math.min((size - 4) / bounds.width, (size - 4) / bounds.height)
  const width = Math.max(1, Math.floor(bounds.width * scale))
  const height = Math.max(1, Math.floor(bounds.height * scale))
  const ox = Math.floor((size - width) / 2)
  const oy = Math.floor((size - height) / 2)

  for (let y = 0; y < height; y++) {
    for (let x = 0; x < width; x++) {
      const sourceX = bounds.x + Math.min(bounds.width - 1, Math.floor(x / scale))
      const sourceY = bounds.y + Math.min(bounds.height - 1, Math.floor(y / scale))
      if (!predicate(src, sourceX, sourceY)) continue
      const sourceIndex = (src.width * sourceY + sourceX) << 2
      const color = tint?.(src.data[sourceIndex], src.data[sourceIndex + 1], src.data[sourceIndex + 2]) ?? [
        src.data[sourceIndex],
        src.data[sourceIndex + 1],
        src.data[sourceIndex + 2],
      ]
      set(tile, ox + x, oy + y, [...color, src.data[sourceIndex + 3]])
    }
  }
}

function isD20RollPixel(src: PNG, x: number, y: number) {
  const index = (src.width * y + x) << 2
  const r = src.data[index]
  const g = src.data[index + 1]
  const b = src.data[index + 2]
  const a = src.data[index + 3]
  if (a < 24) return false

  const redPanel = r > 24 && r > g * 1.8 && r > b * 1.8
  const greyFrame = Math.abs(r - g) < 12 && Math.abs(g - b) < 12 && r > 20 && r < 88
  return !redPanel && !greyFrame
}

function sourceBounds(src: PNG, sx: number, sy: number, sw: number, sh: number, predicate?: (src: PNG, x: number, y: number) => boolean) {
  let minX = sx + sw
  let minY = sy + sh
  let maxX = sx
  let maxY = sy

  for (let y = sy; y < sy + sh; y++) {
    for (let x = sx; x < sx + sw; x++) {
      if (x < 0 || y < 0 || x >= src.width || y >= src.height) continue
      if (predicate) {
        if (!predicate(src, x, y)) continue
      } else {
        const alpha = src.data[((src.width * y + x) << 2) + 3]
        if (alpha < 24) continue
      }
      minX = Math.min(minX, x)
      minY = Math.min(minY, y)
      maxX = Math.max(maxX, x)
      maxY = Math.max(maxY, y)
    }
  }

  if (maxX < minX || maxY < minY) return null
  minX = Math.max(sx, minX - 2)
  minY = Math.max(sy, minY - 2)
  maxX = Math.min(sx + sw - 1, maxX + 2)
  maxY = Math.min(sy + sh - 1, maxY + 2)
  return { x: minX, y: minY, width: maxX - minX + 1, height: maxY - minY + 1 }
}

function humanoid(tile: PNG, id: AnimatedSpriteId, p: ActorPalette, animation: SpriteAnimationId, frame: number) {
  const boss = id.startsWith("boss")
  const ox = animation === "walk" ? [-1, 1, 0, -1][frame] : animation === "attack-melee" ? [0, 1, 2, 0][frame] : 0
  const bob = animation === "idle" || animation === "talk" ? [0, 1, 0, 1][frame] : animation === "hurt" ? 1 : 0
  const cx = 16 + ox
  const headY = boss ? 7 + bob : 9 + bob
  const bodyY = boss ? 14 + bob : 16 + bob
  const scale = boss ? 1 : 0

  ellipse(tile, cx - 5 - scale, headY - 5, cx + 5 + scale, headY + 5, p.dark, true)
  ellipse(tile, cx - 4, headY - 4, cx + 4, headY + 4, p.skin, true)
  fill(tile, cx - 2, headY - 1, 2, 1, [...outline, 255])
  fill(tile, cx + 2, headY - 1, 2, 1, [...outline, 255])
  if (animation === "talk") fill(tile, cx - 2, headY + 3, 4, 1, [...p.accent, 255])
  if (animation === "shocked") {
    fill(tile, cx - 1, headY + 2, 2, 3, [...outline, 255])
    line(tile, cx, headY - 8, cx, headY - 12, p.glow)
  }

  if (id === "boss-minotaur") {
    line(tile, cx - 5, headY - 5, cx - 10, headY - 8, p.accent)
    line(tile, cx + 5, headY - 5, cx + 10, headY - 8, p.accent)
  }

  fill(tile, cx - 7 - scale, bodyY - 2, 14 + scale * 2, 10, [...p.cloth, 255])
  rect(tile, cx - 7 - scale, bodyY - 2, 14 + scale * 2, 10, outline, false)
  fill(tile, cx - 5, bodyY, 10, 3, [...p.armor, 255])
  fill(tile, cx - 2, bodyY - 1, 4, 11, [...p.accent, 255])

  const leftLeg = animation === "walk" ? [-2, 1, 2, -1][frame] : 0
  const rightLeg = -leftLeg
  line(tile, cx - 4, bodyY + 8, cx - 5 + leftLeg, 29, p.dark)
  line(tile, cx + 4, bodyY + 8, cx + 5 + rightLeg, 29, p.dark)

  const melee = animation === "attack-melee"
  const ranged = animation === "attack-ranged"
  const cast = animation === "cast"
  const leftHand = melee ? [cx - 8, bodyY + 2, cx - 13, bodyY - 1] : [cx - 7, bodyY, cx - 11, bodyY + 7]
  const rightHand = melee ? [cx + 7, bodyY, cx + 14, bodyY - 5] : [cx + 7, bodyY, cx + 11, bodyY + 7]
  line(tile, leftHand[0], leftHand[1], leftHand[2], leftHand[3], p.skin)
  line(tile, rightHand[0], rightHand[1], rightHand[2], rightHand[3], p.skin)

  if (id.includes("arcanist") || id.includes("oracle") || id.includes("lich") || id === "necromancer") {
    line(tile, cx + 10, bodyY + 8, cx + 14, bodyY - 9, p.weapon)
    diamond(tile, cx + 14, bodyY - 10, cast ? 5 + (frame % 2) : 3, p.glow)
  } else if (ranged || id.includes("ranger")) {
    arc(tile, cx + 6, bodyY - 2, cx + 16, bodyY + 12, p.weapon)
    line(tile, cx + 7, bodyY - 1, cx + 15, bodyY + 11, [230, 220, 188])
  } else {
    sword(tile, cx + 8, bodyY + 8, cx + 16, melee ? bodyY - 8 : bodyY - 1)
  }

  if (animation === "cast") {
    diamond(tile, cx - 11, bodyY - 4, 3 + (frame % 2), p.glow)
    diamond(tile, cx + 11, bodyY - 7, 2 + (frame % 2), p.accent)
  }
  if (animation === "hurt") line(tile, cx - 8, bodyY - 5, cx + 8, bodyY + 7, [225, 64, 72])
  if (animation === "death") {
    fill(tile, 5, 24, 22, 5, [...p.dark, 230])
    line(tile, 7, 24, 25, 28, p.accent)
  }
}

function slime(tile: PNG, p: ActorPalette, animation: SpriteAnimationId, frame: number) {
  const stretch = animation === "walk" ? [0, 2, 0, -1][frame] : animation === "shocked" ? 3 : 0
  ellipse(tile, 6, 15 - stretch, 26, 28, p.dark, true)
  ellipse(tile, 7, 14 - stretch, 25, 27, p.skin, true)
  ellipse(tile, 11, 16 - stretch, 15, 20, p.accent, true)
  ellipse(tile, 18, 16 - stretch, 22, 20, p.accent, true)
  fill(tile, 12, 21 - stretch, 8, 2, [...p.dark, 255])
  if (animation === "attack-melee") flame(tile, 23, 16, p.skin, p.glow)
  if (animation === "hurt") line(tile, 8, 17, 24, 24, [225, 64, 72])
}

function d20(tile: PNG, result: number, frame: number) {
  const spin = frame % 4
  const base = result === 20 ? [235, 200, 87] : result === 1 ? [171, 67, 84] : [93, 111, 136]
  const glow = result === 20 ? [255, 238, 146] : result === 1 ? [236, 101, 117] : [179, 205, 232]
  diamond(tile, 16 + (spin === 1 ? 1 : spin === 3 ? -1 : 0), 16, 13, darken(base, 0.5))
  diamond(tile, 16, 15, 12, base)
  triangle(tile, 16, 3, 27, 16, 16, 15, lighten(base, 1.22))
  triangle(tile, 5, 16, 16, 3, 16, 15, darken(base, 0.82))
  triangle(tile, 5, 16, 16, 28, 16, 16, darken(base, 0.64))
  triangle(tile, 27, 16, 16, 28, 16, 16, darken(base, 0.74))
  drawNumber(tile, result, 16, 16, glow)
}

function drawD20Frame(tile: PNG, result: number, frame: number) {
  const path = join(openGameArtD20Root, `r${String(result).padStart(2, "0")}.png`)
  if (existsSync(path)) {
    const png = PNG.sync.read(readFileSync(path))
    drawMaskedSourceFrame(tile, png, frame * 512, 0, 512, 512, isD20RollPixel, d20Tint(result))
    return
  }
  d20(tile, result, frame)
}

function d20Tint(result: number) {
  const base: Rgb = result === 20 ? [221, 172, 69] : result === 1 ? [167, 61, 82] : [72, 92, 121]
  const light: Rgb = result === 20 ? [255, 241, 155] : result === 1 ? [242, 127, 145] : [198, 218, 239]
  return (r: number, g: number, b: number): Rgb => {
    const brightness = (r + g + b) / 3
    if (brightness > 170) return light
    if (brightness > 85) return lighten(base, 1.22)
    return base
  }
}

function bottle(tile: PNG, body: Rgb, shade: Rgb) {
  fill(tile, 14, 6, 5, 5, [125, 174, 182, 255])
  rect(tile, 14, 6, 5, 5, outline, false)
  fill(tile, 10, 12, 13, 15, [...shade, 255])
  rect(tile, 10, 12, 13, 15, outline, false)
  fill(tile, 12, 13, 9, 9, [...body, 255])
  fill(tile, 15, 14, 3, 4, [245, 167, 190, 255])
}

function diamondRelic(tile: PNG) {
  diamond(tile, 16, 15, 11, [64, 38, 82])
  diamond(tile, 16, 15, 8, [207, 86, 185])
  diamond(tile, 16, 15, 4, [101, 223, 255])
  line(tile, 16, 4, 16, 26, [246, 213, 104])
}

function chest(tile: PNG) {
  fill(tile, 7, 12, 18, 13, [125, 80, 52, 255])
  rect(tile, 7, 12, 18, 13, outline, false)
  fill(tile, 8, 9, 16, 7, [153, 97, 59, 255])
  rect(tile, 8, 9, 16, 7, outline, false)
  fill(tile, 15, 14, 3, 6, [229, 190, 83, 255])
}

function scroll(tile: PNG) {
  fill(tile, 9, 9, 15, 16, [199, 174, 132, 255])
  rect(tile, 9, 9, 15, 16, [75, 55, 43], false)
  ellipse(tile, 6, 8, 12, 14, [220, 198, 155], true)
  ellipse(tile, 20, 20, 26, 26, [220, 198, 155], true)
  line(tile, 12, 14, 20, 14, [116, 83, 62])
  line(tile, 12, 18, 19, 18, [116, 83, 62])
}

function sword(tile: PNG, x1: number, y1: number, x2: number, y2: number) {
  line(tile, x1, y1, x2, y2, [235, 230, 211])
  line(tile, x1 + 1, y1, x2 + 1, y2, [143, 151, 166])
  fill(tile, x1 - 3, y1 - 2, 7, 3, [126, 82, 45, 255])
  fill(tile, x1 - 1, y1 + 1, 3, 3, [213, 161, 82, 255])
}

function shield(tile: PNG) {
  fill(tile, 10, 8, 12, 15, [68, 79, 99, 255])
  rect(tile, 10, 8, 12, 15, outline, false)
  fill(tile, 13, 10, 6, 11, [184, 126, 74, 255])
  line(tile, 16, 8, 16, 23, [229, 190, 83])
}

function flame(tile: PNG, cx: number, cy: number, outer: Rgb, inner: Rgb) {
  triangle(tile, cx, cy - 12, cx - 8, cy + 6, cx + 8, cy + 6, outer)
  triangle(tile, cx + 2, cy - 7, cx - 4, cy + 7, cx + 5, cy + 7, inner)
}

function createSheet(columns: number, rows: number, clear: boolean) {
  const png = new PNG({ width: columns * size, height: rows * size })
  const fillColor = clear ? transparent : [5, 7, 10, 255] satisfies Rgba
  for (let y = 0; y < png.height; y++) {
    for (let x = 0; x < png.width; x++) set(png, x, y, fillColor)
  }
  return png
}

function drawTile(sheet: PNG, tileX: number, tileY: number, draw: (tile: PNG) => void) {
  const tile = createSheet(1, 1, true)
  draw(tile)
  blit(tile, sheet, tileX * size, tileY * size)
}

function savePng(png: PNG, filename: string) {
  writeFileSync(join(outDir, filename), PNG.sync.write(upscaleNearest(png, upscaleFactor)))
}

function upscaleNearest(src: PNG, factor: number) {
  if (factor === 1) return src

  const dst = new PNG({ width: src.width * factor, height: src.height * factor })
  for (let y = 0; y < src.height; y++) {
    for (let x = 0; x < src.width; x++) {
      const index = (src.width * y + x) << 2
      const color: Rgba = [src.data[index], src.data[index + 1], src.data[index + 2], src.data[index + 3]]
      for (let yy = 0; yy < factor; yy++) {
        for (let xx = 0; xx < factor; xx++) set(dst, x * factor + xx, y * factor + yy, color)
      }
    }
  }
  return dst
}

function blit(src: PNG, dst: PNG, dx: number, dy: number) {
  for (let y = 0; y < src.height; y++) {
    for (let x = 0; x < src.width; x++) {
      const index = (src.width * y + x) << 2
      set(dst, dx + x, dy + y, [src.data[index], src.data[index + 1], src.data[index + 2], src.data[index + 3]])
    }
  }
}

function set(png: PNG, x: number, y: number, color: Rgba | Rgb) {
  if (x < 0 || y < 0 || x >= png.width || y >= png.height) return
  const index = (png.width * Math.round(y) + Math.round(x)) << 2
  png.data[index] = color[0]
  png.data[index + 1] = color[1]
  png.data[index + 2] = color[2]
  png.data[index + 3] = color[3] ?? 255
}

function fill(png: PNG, x: number, y: number, width: number, height: number, color: Rgba) {
  for (let yy = y; yy < y + height; yy++) {
    for (let xx = x; xx < x + width; xx++) set(png, xx, yy, color)
  }
}

function rect(png: PNG, x: number, y: number, width: number, height: number, color: Rgb, filled: boolean) {
  if (filled) {
    fill(png, x, y, width, height, [...color, 255])
    return
  }
  line(png, x, y, x + width - 1, y, color)
  line(png, x, y + height - 1, x + width - 1, y + height - 1, color)
  line(png, x, y, x, y + height - 1, color)
  line(png, x + width - 1, y, x + width - 1, y + height - 1, color)
}

function line(png: PNG, x0: number, y0: number, x1: number, y1: number, color: Rgb) {
  let x = Math.round(x0)
  let y = Math.round(y0)
  const endX = Math.round(x1)
  const endY = Math.round(y1)
  const dx = Math.abs(endX - x)
  const sx = x < endX ? 1 : -1
  const dy = -Math.abs(endY - y)
  const sy = y < endY ? 1 : -1
  let error = dx + dy

  while (true) {
    set(png, x, y, [...color, 255])
    if (x === endX && y === endY) break
    const doubled = 2 * error
    if (doubled >= dy) {
      error += dy
      x += sx
    }
    if (doubled <= dx) {
      error += dx
      y += sy
    }
  }
}

function ellipse(png: PNG, x0: number, y0: number, x1: number, y1: number, color: Rgb, filled: boolean) {
  const cx = (x0 + x1) / 2
  const cy = (y0 + y1) / 2
  const rx = Math.max(1, (x1 - x0) / 2)
  const ry = Math.max(1, (y1 - y0) / 2)
  for (let y = Math.floor(y0); y <= Math.ceil(y1); y++) {
    for (let x = Math.floor(x0); x <= Math.ceil(x1); x++) {
      const d = ((x - cx) * (x - cx)) / (rx * rx) + ((y - cy) * (y - cy)) / (ry * ry)
      if (filled ? d <= 1 : d > 0.74 && d <= 1.16) set(png, x, y, [...color, 255])
    }
  }
}

function diamond(png: PNG, cx: number, cy: number, radius: number, color: Rgb) {
  for (let y = cy - radius; y <= cy + radius; y++) {
    const half = radius - Math.abs(y - cy)
    line(png, cx - half, y, cx + half, y, color)
  }
  line(png, cx, cy - radius, cx + radius, cy, darken(color, 0.45))
  line(png, cx + radius, cy, cx, cy + radius, darken(color, 0.45))
  line(png, cx, cy + radius, cx - radius, cy, darken(color, 0.45))
  line(png, cx - radius, cy, cx, cy - radius, darken(color, 0.45))
}

function triangle(png: PNG, ax: number, ay: number, bx: number, by: number, cx: number, cy: number, color: Rgb) {
  const minX = Math.floor(Math.min(ax, bx, cx))
  const maxX = Math.ceil(Math.max(ax, bx, cx))
  const minY = Math.floor(Math.min(ay, by, cy))
  const maxY = Math.ceil(Math.max(ay, by, cy))
  const area = edge(ax, ay, bx, by, cx, cy)
  for (let y = minY; y <= maxY; y++) {
    for (let x = minX; x <= maxX; x++) {
      const w0 = edge(bx, by, cx, cy, x, y)
      const w1 = edge(cx, cy, ax, ay, x, y)
      const w2 = edge(ax, ay, bx, by, x, y)
      if ((area >= 0 && w0 >= 0 && w1 >= 0 && w2 >= 0) || (area < 0 && w0 <= 0 && w1 <= 0 && w2 <= 0)) set(png, x, y, [...color, 255])
    }
  }
}

function edge(ax: number, ay: number, bx: number, by: number, px: number, py: number) {
  return (px - ax) * (by - ay) - (py - ay) * (bx - ax)
}

function arc(png: PNG, x0: number, y0: number, x1: number, y1: number, color: Rgb) {
  const cx = (x0 + x1) / 2
  const cy = (y0 + y1) / 2
  const rx = Math.abs(x1 - x0) / 2
  const ry = Math.abs(y1 - y0) / 2
  for (let a = -80; a <= 80; a += 6) {
    const radians = (a * Math.PI) / 180
    set(png, Math.round(cx + Math.cos(radians) * rx), Math.round(cy + Math.sin(radians) * ry), [...color, 255])
  }
}

function drawNumber(png: PNG, value: number, cx: number, cy: number, color: Rgb) {
  const text = String(value)
  const start = cx - text.length * 3
  for (let index = 0; index < text.length; index++) drawDigit(png, Number(text[index]), start + index * 6, cy - 4, color)
}

function drawDigit(png: PNG, digit: number, x: number, y: number, color: Rgb) {
  const segments: Record<number, string> = {
    0: "abcfed",
    1: "bc",
    2: "abged",
    3: "abgcd",
    4: "fgbc",
    5: "afgcd",
    6: "afgecd",
    7: "abc",
    8: "abcdefg",
    9: "abfgcd",
  }
  const draw = segments[digit] ?? ""
  if (draw.includes("a")) line(png, x, y, x + 4, y, color)
  if (draw.includes("b")) line(png, x + 4, y, x + 4, y + 4, color)
  if (draw.includes("c")) line(png, x + 4, y + 4, x + 4, y + 8, color)
  if (draw.includes("d")) line(png, x, y + 8, x + 4, y + 8, color)
  if (draw.includes("e")) line(png, x, y + 4, x, y + 8, color)
  if (draw.includes("f")) line(png, x, y, x, y + 4, color)
  if (draw.includes("g")) line(png, x, y + 4, x + 4, y + 4, color)
}

function scatter(png: PNG, seed: number, light: Rgb, dark: Rgb) {
  for (let i = 0; i < 28; i++) {
    const x = (seed * 17 + i * 11) % size
    const y = (seed * 23 + i * 7) % size
    set(png, x, y, [...(i % 2 ? light : dark), 255])
  }
}

function lighten(color: Rgb, factor: number): Rgb {
  return color.map((component) => clamp(Math.round(component * factor), 0, 255)) as Rgb
}

function darken(color: Rgb, factor: number): Rgb {
  return lighten(color, factor)
}

function clamp(value: number, min: number, max: number) {
  return Math.max(min, Math.min(max, value))
}
